codecov:
  token: 1a85424a-8aaa-475c-bdf7-48c2925ad12b
  ci:
    - "travis.org"
  require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "50...100"  # value range where you want the value to be green
